CREATE SYNONYM stocks
FOR inventories;

SELECT * FROM stocks;

CREATE TABLE DEMO(
ID NUMBER GENERATED AS IDENTITY,
DATA VARCHAR2(10)
);

INSERT INTO DEMO (DATA) VALUES ('RECORD1');
INSERT INTO DEMO (DATA) VALUES ('RECORD2');
INSERT INTO DEMO (DATA) VALUES ('RECORD3');
INSERT INTO DEMO (DATA) VALUES ('RECORD4');
INSERT INTO DEMO (DATA) VALUES ('RECORD5');
COMMIT;
SELECT  * FROM DEMO;

CREATE SYNONYM SYN_DEMO FOR C##ADUSER.DEMO;

SELECT * FROM SYN_DEMO;

SELECT * FROM c##aduser.syn_demo;


